-- Data wilayah untuk pilihan jangkauan mitra.
-- Jalankan di Supabase SQL Editor.

create table if not exists wilayah_malang (
  id_wilayah bigint generated by default as identity primary key,
  nama varchar(120) not null,
  tipe varchar(20) not null check (tipe in ('provinsi', 'kota', 'kecamatan', 'kelurahan')),
  parent_nama varchar(120),
  dibuat_pada timestamptz not null default now(),
  unique (nama, tipe, parent_nama)
);

insert into wilayah_malang (nama, tipe, parent_nama)
values
  ('Jawa Timur', 'provinsi', null),
  ('Malang', 'kota', 'Jawa Timur'),
  ('Blimbing', 'kecamatan', 'Malang'),
  ('Kedungkandang', 'kecamatan', 'Malang'),
  ('Klojen', 'kecamatan', 'Malang'),
  ('Lowokwaru', 'kecamatan', 'Malang'),
  ('Sukun', 'kecamatan', 'Malang'),
  ('Arjosari', 'kelurahan', 'Blimbing'),
  ('Blimbing', 'kelurahan', 'Blimbing'),
  ('Ciptomulyo', 'kelurahan', 'Sukun'),
  ('Dinoyo', 'kelurahan', 'Lowokwaru'),
  ('Jodipan', 'kelurahan', 'Blimbing'),
  ('Kasin', 'kelurahan', 'Klojen'),
  ('Kepanjen', 'kelurahan', 'Kedungkandang'),
  ('Lowokwaru', 'kelurahan', 'Lowokwaru'),
  ('Mergosono', 'kelurahan', 'Kedungkandang'),
  ('Samaan', 'kelurahan', 'Klojen'),
  ('Tlogomas', 'kelurahan', 'Lowokwaru'),
  ('Tulusrejo', 'kelurahan', 'Lowokwaru')
on conflict (nama, tipe, parent_nama) do nothing;

create index if not exists idx_wilayah_malang_parent
  on wilayah_malang (tipe, parent_nama, nama);

notify pgrst, 'reload schema';