-- Struktur manajemen pekerjaan Mitra.
-- Jalankan di Supabase SQL Editor setelah tabel users, mitra_profil,
-- dan kategori_layanan tersedia.

create table if not exists mitra_layanan (
  id_layanan_mitra bigint generated by default as identity primary key,
  mitra_id integer not null references users(id_user) on delete cascade,
  katagori_id integer not null references kategori_layanan(id_katagori) on delete restrict,
  tarif_mulai numeric(14,2) not null default 0 check (tarif_mulai >= 0),
  tarif_selesai numeric(14,2) check (tarif_selesai is null or tarif_selesai >= tarif_mulai),
  satuan_tarif varchar(50) not null default 'per layanan',
  aktif boolean not null default true,
  dibuat_pada timestamptz not null default now(),
  diperbarui_pada timestamptz not null default now(),
  unique (mitra_id, katagori_id)
);

create index if not exists idx_mitra_layanan_mitra
  on mitra_layanan (mitra_id, aktif);

create table if not exists mitra_jadwal_kerja (
  id_jadwal_mitra bigint generated by default as identity primary key,
  mitra_id integer not null references users(id_user) on delete cascade,
  hari smallint not null check (hari between 1 and 7),
  aktif boolean not null default true,
  jam_mulai time not null,
  jam_selesai time not null,
  dibuat_pada timestamptz not null default now(),
  diperbarui_pada timestamptz not null default now(),
  unique (mitra_id, hari),
  check (jam_selesai > jam_mulai)
);

create index if not exists idx_mitra_jadwal_mitra
  on mitra_jadwal_kerja (mitra_id, aktif);

create table if not exists mitra_area_operasional (
  id_area_mitra bigint generated by default as identity primary key,
  mitra_id integer not null references users(id_user) on delete cascade,
  nama_area varchar(150) not null,
  radius_km numeric(8,2) not null default 10 check (radius_km > 0),
  aktif boolean not null default true,
  dibuat_pada timestamptz not null default now(),
  diperbarui_pada timestamptz not null default now(),
  unique (mitra_id, nama_area)
);

create index if not exists idx_mitra_area_mitra
  on mitra_area_operasional (mitra_id, aktif);

create table if not exists mitra_sertifikasi (
  id_sertifikasi_mitra bigint generated by default as identity primary key,
  mitra_id integer not null references users(id_user) on delete cascade,
  nama_sertifikasi varchar(150) not null,
  nomor_sertifikasi varchar(100),
  penerbit varchar(150),
  berlaku_mulai date,
  berlaku_sampai date,
  dokumen_url text,
  status_verifikasi varchar(30) not null default 'menunggu'
    check (status_verifikasi in ('menunggu', 'terverifikasi', 'ditolak')),
  dibuat_pada timestamptz not null default now(),
  diperbarui_pada timestamptz not null default now()
);

create index if not exists idx_mitra_sertifikasi_mitra
  on mitra_sertifikasi (mitra_id, status_verifikasi);

alter table mitra_layanan enable row level security;
alter table mitra_jadwal_kerja enable row level security;
alter table mitra_area_operasional enable row level security;
alter table mitra_sertifikasi enable row level security;

create or replace function public.current_mitra_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select id_user from users where auth_uid = auth.uid() limit 1;
$$;

drop policy if exists "Mitra melihat layanan sendiri" on mitra_layanan;
drop policy if exists "Mitra mengelola layanan sendiri" on mitra_layanan;
create policy "Mitra melihat layanan sendiri"
  on mitra_layanan for select
  using (mitra_id = public.current_mitra_id());
create policy "Mitra mengelola layanan sendiri"
  on mitra_layanan for all
  using (mitra_id = public.current_mitra_id())
  with check (mitra_id = public.current_mitra_id());

drop policy if exists "Mitra melihat jadwal sendiri" on mitra_jadwal_kerja;
drop policy if exists "Mitra mengelola jadwal sendiri" on mitra_jadwal_kerja;
create policy "Mitra melihat jadwal sendiri"
  on mitra_jadwal_kerja for select
  using (mitra_id = public.current_mitra_id());
create policy "Mitra mengelola jadwal sendiri"
  on mitra_jadwal_kerja for all
  using (mitra_id = public.current_mitra_id())
  with check (mitra_id = public.current_mitra_id());

drop policy if exists "Mitra melihat area sendiri" on mitra_area_operasional;
drop policy if exists "Mitra mengelola area sendiri" on mitra_area_operasional;
create policy "Mitra melihat area sendiri"
  on mitra_area_operasional for select
  using (mitra_id = public.current_mitra_id());
create policy "Mitra mengelola area sendiri"
  on mitra_area_operasional for all
  using (mitra_id = public.current_mitra_id())
  with check (mitra_id = public.current_mitra_id());

drop policy if exists "Mitra melihat sertifikasi sendiri" on mitra_sertifikasi;
drop policy if exists "Mitra mengelola sertifikasi sendiri" on mitra_sertifikasi;
create policy "Mitra melihat sertifikasi sendiri"
  on mitra_sertifikasi for select
  using (mitra_id = public.current_mitra_id());
create policy "Mitra mengelola sertifikasi sendiri"
  on mitra_sertifikasi for all
  using (mitra_id = public.current_mitra_id())
  with check (mitra_id = public.current_mitra_id());
